### ISSUE TITLE
service port

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot-deployment#11]
I've been trying to deploy release bot (built from https://github.com/user-cont/release-bot/pull/237) in my local 'oc cluster' and I'm not able to access it.
Trying to POST something to `http://release-bot-myproject.127.0.0.1.nip.io/webhook-handler/` still returns `503 Service Unavailable`.

Release bot seems to [run on `8080`](https://github.com/user-cont/release-bot/pull/237/files#diff-f1ac561b7c15a0f811b902a4bd0f84f8L73), while the [openshift/service.yml](https://github.com/user-cont/release-bot-deployment/blob/master/openshift/service.yml#L36) says `8443`.
Any ideas what I might be missing?

**Comment by marusinm** [comment]
Since you are using `oc cluster` commnad I guess you have OpenShift 3.x. I am using OpenShift Online 4.1 and deployment is running without problems. When I look into YML file of running service which you mentioned I see this:
```
ports:
    - name: prod-release-bot
      protocol: TCP
      port: 443
      targetPort: 8080
```
So all communication via 443 should be forwarded to 8080 inner port of the pod if I understand correctly. 

If you'll try OpenShift Online please build the image and push to docker hub. I was using marusinm/release-bot image instead of usercont/release-bot which is now in the Makefile.

**Comment by jpopelka** [comment]
> I guess you have OpenShift 3.x.

yes

> When I look into YML file of running service which you mentioned I see this:
> targetPort: 8080

Then you must have edited it or something because [the service.yml](https://github.com/user-cont/release-bot-deployment/blob/master/openshift/service.yml#L36) says `8443`.

> please build the image and push to docker hub

will do once I make 'container-things' work in F31 to which I've just upgraded

**Comment by marusinm** [comment]
>Then you must have edited it or something because the service.yml says 8443

Yes, you are right I missed it somehow. Sorry, I opened PR #13
